name: generate_yaml_wls

on:
  schedule:
    - cron: '0 0 * * 6' #At 00:00 on Saturday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install dependencies
        run: python3 -m pip install PyYAML requests

      - name: Run generate_yaml_lists
        run: python3 scripts/yaml_lists/generate_yaml_lists.py

      - name: Create local changes
        run: git add .

      - name: Commit results to Github
        run: |
            git config --local user.email ""
            git config --global user.name "yamllists"
            git commit -m "Bot yamllists auto update" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
