name: generate_trusted_resolvers_wl

on:
  #schedule:
  #  - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Checkout dnsvalidator
        run: git clone https://github.com/vortexau/dnsvalidator.git

      - name: Install dnsvalidator
        run: |
            cd dnsvalidator
            sudo python3 setup.py install
            cd --

      - name: Run dnsvalidator
        run: dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 20 -o wordlists/trusted_resolvers.txt

      - name: Create local changes
        run: git add wordlists/trusted_resolvers.txt

      - name: Commit results to Github
        run: |
            git config --local user.email ""
            git config --global user.name "trusted_resolvers"
            git commit -m "Bot trusted_resolvers auto update" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
